FROM pytorch/pytorch

ENV APP_HOME=/home/app/web
RUN mkdir -p ${APP_HOME}
WORKDIR ${APP_HOME}

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.dev.txt .
RUN pip install -r requirements.dev.txt

COPY . . 